### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by hansbred** [jbouwh/ha-elro-connects#20] opened 2022-11-23 22:08 UTC
I have setup Home Automation in a Docker container and added HACS and elro-components.
After configuring, first just with the connector Id, later with username and password which retrieved the same connector id I added manually in the first round and API key (wasn't retrieved when only using the connector id), I keep on getting the following error:

Config entry 'Elro Connects K1 Connector' for elro_connects integration not ready yet: Not received the expected result, cannot connect to hub 192.168.xxx.xxx with id "ST_............". ('Expecting property name enclosed in double quotes: line 1 column 2 (char 1)',); Retrying in background.
The connector id is all lowercase hex, changing this to upper case didn't work neither did enclosing it in double quotes

**Comment by jbouwh** [comment] 2022-12-19 08:47
Sorry for the late reply. Did you manage to get it to work?

**Comment by jbouwh** [comment] 2023-01-12 10:10
Will close this issue. Cannot reproduce this issue.

**Closed by jbouwh** 2023-01-12 10:10 UTC
