### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by TAGVL** [jbouwh/ha-elro-connects#25] opened 2023-01-05 10:47 UTC
When I put in ip address, credentials and even connector ID I get message unable to connect. Also tried without credentials but similar result. Running HA2023.1

I have the Elro connected to guest wifi since this is the only 2.4ghz and the dual band the K1 can't connect to. Might this be the issue? The ip is in similar range as all other local ip's. Any idea how I can connect to the K1 integration?

**Comment by TAGVL** [comment] 2023-01-05 10:49
![EA1ECB75-D81E-48EE-9851-3BB65F63FDA0](https://user-images.githubusercontent.com/78881168/210762792-9a5d10b6-f896-4c2b-a036-1d59e7b322dc.jpeg)
![7D7BAE2C-D9CF-4CFC-B65A-A7ED63D03F37](https://user-images.githubusercontent.com/78881168/210762794-c1c2b9f4-808b-423a-a23f-1d3a843ba879.png)

**Comment by jbouwh** [comment] 2023-01-05 15:48
You'll need a direct ip connection to you connector for this integration to work

**Comment by jbouwh** [comment] 2023-01-05 20:08
Tested with the latest version in my own environment, I can not reproduce the issue you are having.

**Comment by TAGVL** [comment] 2023-01-05 20:24
Oké, so it should be possible with the Elro in guest (2.4ghz) wifi and all the rest in main (5/2.4ghz)? Then I will try again tomorrow some timea

**Comment by jbouwh** [comment] 2023-01-05 20:28
First you need to enroll the device with the Elro Connects app. You could temporary turn off 5 GHz. After the device is connected you can enable it again. The smartphone used to enroll needs to be connected to 2.4 GHz WiFi. After the device is installed you can use the integration in Home Assistant.

**Comment by jbouwh** [comment] 2023-01-09 07:18
Closing here, since this is not an issue with the integration.

**Closed by jbouwh** 2023-01-09 07:18 UTC
